# Generated by Django 5.0.4 on 2024-05-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='all_users',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
