# Generated by Django 5.0.4 on 2024-05-20 15:24

import file.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_documentcategory_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='file/documents/', validators=[file.validations.document_file_validation]),
        ),
    ]
