# Generated by Django 5.0.4 on 2024-05-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_contactadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='contactadmin',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Admin Messages'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Document Categories'},
        ),
    ]
