# Generated by Django 5.0.4 on 2024-05-29 01:27

import file.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_alter_all_users_options_alter_contactadmin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(unique=True, upload_to='file/documents/', validators=[file.validations.document_file_validation]),
        ),
    ]
